CoderDojo/cp-users-service

- agreements.js
- package.json
Don't allow user to sign charter multiple times.
ref https://github.com/CoderDojo/community-platform/issues/655
> validation fixes

- profiles.js
ref https://github.com/CoderDojo/community-platform/issues/685
> don't return fatal error if profile avatar is not an image on upload or size exceeds 5MB

- profiles.js
ref https://github.com/CoderDojo/community-platform/issues/669
> allow cdf admins to add ninjas

- users.js
Should resolve https://github.com/CoderDojo/community-platform/issues/745.
> Use args.user.id if no userId passed.

- email-templates/auth-create-reset-en_US/users-auth-create-reset.html.ejs
- email-templates/auth-create-reset-en_US/users-auth-create-reset.text.ejs
- email-templates/auth-register-en_US/users-auth-register.html.ejs
- email-templates/auth-register-en_US/users-auth-register.text.ejs
- email-templates/invite-ninja-over-13-en_US/users-invite-ninja-over-13.html.ejs
- email-templates/invite-ninja-over-13-en_US/users-invite-ninja-over-13.text.ejs
- email-templates/invite-parent-guardian-en_US/invite-parent-guardian.html.ejs
- email-templates/invite-parent-guardian-en_US/invite-parent-guardian.text.ejs
https://github.com/CoderDojo/community-platform/issues/614
> Update email templates

- profiles.js
- users.js
ref https://github.com/CoderDojo/community-platform/issues/745
ref https://github.com/CoderDojo/community-platform/issues/797
> fixed issues caused by load_dojo_admins_for_user

- package.json
installed pre-commit as dev dependency
> upgrade seneca to use 0.7.2

- profiles.js
ref https://github.com/CoderDojo/community-platform/issues/806
> allow under13 users to see their own profiles

- users.js
Requires https://github.com/CoderDojo/cp-zen-platform/pull/772
> Rename ninja to youth to avoid confusion

- profiles.js
Fixes https://github.com/CoderDojo/community-platform/issues/880
> Correct name of endpoint

- email-templates/invite-ninja-over-13-en_US/users-invite-ninja-over-13.html.ejs
- email-templates/invite-ninja-over-13-en_US/users-invite-ninja-over-13.text.ejs
- email-templates/invite-parent-guardian-en_US/invite-parent-guardian.html.ejs
- email-templates/invite-parent-guardian-en_US/invite-parent-guardian.text.ejs
https://github.com/CoderDojo/community-platform/issues/676
Simple change to email templates to add line "In order to accept this invite, you will need to register for an account on Zen.".
> Add text to advise invitees to register

- test/lib/test-user-data.js
I know that the cp-e2e-tests describe how to change this file. I suggest these names are added by default so one does not need to edit this file.
> added test users for cp-e2e-tests

- circle.yml
- crowdin.yaml
> add circle file

- .gitignore
- crowdin.yaml
- email-notifications.js
- package.json
- profiles.js
- users.js
- web/locale/en_US/messages.po
Requires CoderDojo/cp-zen-platform#913, CoderDojo/cp-events-service#109. and CoderDojo/cp-dojos-service#265
> Moved email subject translation to back-end

- circle.yml
for [#988](https://github.com/CoderDojo/community-platform/issues/988)
> add maltese slovenian slovak ukrainian french and Argentinian

- profiles.js
> Make user profile public by exposing the user id

- config/perm/profiles.js
- config/perm/users.js
Should close https://github.com/CoderDojo/cd-common/issues/12#issuecomment-250930640
> Extend champion userType for perms

- lib/users/lms/award-badge.js
- lib/users/lms/get-lms-link.js
TODO : define LMS_API_URL in production
> Invite users when email already used in LMS

- config/perm/profiles.js
- lib/profiles/load-children-for-user.js
- profiles.js
Needed for CoderDojo/cp-zen-platform#1066 and CoderDojo/cd-common#16
> Added load_children_for_user for My Children page

- profiles.js
Close https://github.com/CoderDojo/community-platform/issues/1202
> Fix issue where user updating their name was not updating their sys_name

- lib/fixes/1202-sync-sys-user-profile.js
- profiles.js
To be called w/ 
`curl -d '{"role": "cd-profiles", "cmd":"1202_syncSysUserName"}' http://localhost:10303/act`
> Backfill script for #1202

- profiles.js
see https://github.com/Joris-van-der-Wel/node-pg-large-object/issues/5
> ROLLBACK transaction when failing loading LOB for avatar

- .dockerignore
- dev.Dockerfile
- docker-entrypoint.sh
dockerfile for development env to be used with a volume
> add dev dockerfile

- profiles.js
Fixes https://github.com/CoderDojo/community-platform/issues/1218
> Fix avatar upload due to hapijs upgrade

- lib/profiles/alias-generator.js
- profiles.js
fix a bug when no firstname lastname is provided but an alias exists
> Fix a bug where the u13 email was saved to profile (but not sys_user)

- config/perm/users.js
Requires https://github.com/CoderDojo/cp-zen-platform/pull/1290
> Reduce perm to lookup prev founder to CDF

- lib/users/is-parent-of.js
Solves  https://forums.coderdojo.com/topic/678/parent-account-corrupted-after-deleting-a-duplicate-child/2
> Add qs "id"  as a possible source of value for the perm isParentOf

- config/perm/profiles.js
register doesnt use this endpoint if you're concerned
> Ensure perms for saving a profile is self

- nodebb-api.js
- oauth2.js
- profiles.js
Redirect unlogged flow back to the start of the flow to get a valid crsf token
> Add state to the workflow

- nodebb-api.js
- oauth2.js
- profiles.js
Reverts CoderDojo/cp-users-service#301
> Revert "Add state to the workflow"

- lib/profile-utils.js
- package.json
- scripts/database/pg/migrations/027.do.add-profile-hash.sql
- users.js
- yarn.lock
- Add profile_password column to sys_users db
- On login, if profile_password column not populated, encode and save.
- On reset password or register, encode and save password to profile_password column.
Resolves #307
> Profile password hashes

- profiles.js
- users.js
Remove `alias` from fields that count towards a complete profile as it
isn't needed and was still counting a null value as complete anyway.
> Allow accepting T&Cs from profile edit page

- .circleci/config.yml
context: docker-hub, bastion-cluster-access
> Update circleci config.yml to use context
